import = [
"~/.config/alacritty/catppuccin-latte.toml",
]

[font]
normal = { family = "BlexMono Nerd Font Mono", style = "Regular" }
size = 16

[window]
option_as_alt = "Both"
decorations = "Buttonless"
dynamic_padding = true
resize_increments = true
