[colors.primary]
background = "#e3e5e9"
#"#eff1f5"
foreground = "#4c4f69"
dim_foreground = "#8c8fa1"
bright_foreground = "#4c4f69"

[colors.cursor]
text = "#e3e5e9"
#"#eff1f5"
# cursor = "#7287fd" # lavender
# cursor = "#04a5e5" # teal
# cursor = "#1e66f5" # blue
# cursor = "#40a02b" # green
cursor = "#ea76cb" # pink
# cursor = "#dc8a78" # rosewater

[colors.vi_mode_cursor]
text = "#e3e5e9"
#"#eff1f5"
cursor = "#7287fd"

[colors.search.matches]
foreground = "#e3e5e9"
#"#eff1f5"
background = "#6c6f85"

[colors.search.focused_match]
foreground = "#e3e5e9"
#"#eff1f5"
background = "#40a02b"

[colors.footer_bar]
foreground = "#e3e5e9"
#"#eff1f5"
background = "#6c6f85"

[colors.hints.start]
foreground = "#e3e5e9"
#"#eff1f5"
background = "#df8e1d"

[colors.hints.end]
foreground = "#e3e5e9"
#"#eff1f5"
background = "#6c6f85"

[colors.selection]
text = "#e3e5e9"
#"#eff1f5"
background = "#dc8a78"

[colors.normal]
black = "#bcc0cc"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb" # pink
cyan = "#179299"
white = "#5c5f77"

[colors.bright]
black = "#acb0be"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#6c6f85"

[[colors.indexed_colors]]
index = 16
color = "#fe640b"

[[colors.indexed_colors]]
index = 17
color = "#dc8a78"
