# override the host_* keys in {{ ansible_hostname }}.config.yml
# or default.config.yml to extend lists/script
host_brew_packages: []
host_brew_casks: []
host_npm_packages: []
host_gems: []
host_mvn_artifacts: []
host_stow_packages: []

brew_packages:
  - autopep8
  - basedpyright
  - bat
  - bear
  - bitwarden-cli
  - btop
  - composer
  - coreutils
  - deno
  - direnv
  - fd
  - ffmpeg
  - fzf
  - gh
  - git
  - go
  - google-java-format
  - gopls
  - gpatch
  - gradle
  - harper
  - htop
  - jdtls
  - julia
  - lua
  - lua-language-server
  - luajit
  - luarocks
  - mas
  - maven
  - neovim
  - node
  - pandoc
  - php
  - pipx
  - prettier
  - python-setuptools
  - ripgrep
  - ruby-install
  - rust
  - sox
  - stow
  - stylua
  - terraform
  - tmux
  - tree
  - uv
  - viu
  - wget
  - yaml-language-server
  - zsh-vi-mode

brew_casks:
  - alacritty

npm_packages:
  - vscode-langservers-extracted # html-lsp, css-lsp
  - dot-language-server

gems:
  - bundler

mvn_artifacts:
  - group_id: org.projectlombok
    artifact_id: lombok

stow_packages:
  - alacritty
  - tmux
  - nvim
  - direnv
  - scripts

zshrc:
  script: |
    # hook in direnv
    eval "$(direnv hook zsh)"

    # set up vi mode plugin
    source $(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
    export ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLINKING_BEAM
    export ZVM_VI_HIGHLIGHT_BACKGROUND=cyan
    export ZVM_VI_HIGHLIGHT_FOREGROUND=white

    # fzf hook
    init_fzf() {
      FZF_ALT_C_COMMAND="--reverse --walker=dir,follow --scheme=path"
      FZF_CTRL_T_OPTS="--preview='bat -n --color=always {}' --preview-window='right:60%:right' --walker-skip='.git'"
      source <(fzf --zsh)
    }
    zvm_after_init_commands+=(init_fzf)

    # bat config
    export BAT_THEME="OneHalfLight"

    # scripts setup
    export PATH="$HOME/.local/share/scripts:$PATH"
    fzf-safari-history() {
      . fzf-safari-history.sh
    }
    zle -N fzf-safari-history
    bindkey -M vicmd '^U' fzf-safari-history
    bindkey -M viins '^U' fzf-safari-history

    # prompt settings
    setopt PROMPT_SUBST
    PROMPT="[%B%F{cyan}%2~%f%b] ➜ "
    RPROMPT=

    # go config
    export GOPATH=$HOME/go

    # java config
    export JAVA_HOME="$(/usr/libexec/java_home -v 21)"
    export GRADLE_USER_HOME="$HOME/.gradle"

    # unixy config
    export LS_COLORS=$(gdircolors)
    export VISUAL=nvim
    export EDITOR=nvim

    # brew config
    export HOMEBREW_NO_ENV_HINTS=1

    # helpful aliases
    alias glog='git log --oneline --graph'

    # general completion
    autoload -U compinit; compinit

    # conditional lazy loaded uv & uvx completion
    uv() {
            unfunction uv
            which uv &> /dev/null && eval "$(uv generate-shell-completion zsh)"
            command uv "$@"
    }
    uvx() {
            unfunction uvx
            which uvx &> /dev/null && eval "$(uvx --generate-shell-completion zsh)"
            command uvx "$@"
    }

zprofile:
  script: |
    export PATH="$PATH:$HOME/.local/bin"
