- name: bootstrap lucy's devenv
  hosts: local

  vars_files: 
    - config.yml
    - [ "{{ ansible_hostname }}.config.yml", config.yml ]

  tasks:
  - name: consolidate variables
    ansible.builtin.set_fact:
      brew_packages: "{{ brew_packages + host_brew_packages }}"
      brew_casks: "{{ brew_casks + host_brew_casks }}"
      stow_packages: "{{ stow_packages + host_stow_packages }}"
      npm_packages: "{{ npm_packages + host_npm_packages }}"
    tags: [ "always" ]

  - name: bootstrap brew packages
    import_role:
      name: brew
    tags: [ "brew" ]
    when: ansible_distribution == "MacOSX"

  - name: install npm packages
    import_role:
      name: npm
    tags: [ "npm" ]

  - name: stow configurations
    import_role:
      name: stow
    tags: [ "stow" ]

  - name: setup zsh
    import_role:
      name: zsh
    tags: [ "zsh" ]
    when: ansible_distribution == "MacOSX"
